version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=contacts_db
      - NODE_ENV=development
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contacts_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./mock-data.sql:/docker-entrypoint-initdb.d/mock-data.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: